{% set name = "orcid" %}
{% set version = "1.0.3" %}
{% set sha256 = "5fe28b6d92aed5abe7145c959e4fa2afb90260be215ff3f36ad31c94ee41d0db" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4
    - simplejson
    - requests
    - lxml
    - html5lib

test:
  requires:
    - python {{ python_min }}
  imports:
    - orcid

about:
  home: https://github.com/ORCID/python-orcid
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python wrapper around ORCID API'

  description: |
    ORCID is an open, non-profit, community-based effort to provide a registry
    of unique researcher identifiers and a transparent method of linking research
    activities and outputs to these identifiers. ORCID is unique in its ability to
    reach across disciplines, research sectors, and national boundaries and its
    cooperation with other identifier systems. orcid is a Python wrapper around
    the ORCID API
  dev_url: https://github.com/ORCID/python-orcid

extra:
  recipe-maintainers:
    - bryanwweber
